site_name: Kachmazov's docs
nav:
  - Главная: index.md
  - №1 Отчёт: lab1.md
  - №2 Отчёт: lab2.md
  - Контакты: contacts.md
theme:
  name: mkdocs
  locale: ru
  color_mode: dark
  custom_dir: assets/